Tower menu update
Now calling on fucntion but need to fill all parameters in this case the position.

Traceback (most recent call last):
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 654, in <module>
    g.run()
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 77, in run
    self.add_tower(tower_menu_button)
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 171, in add_tower
    object_list = [QuickArcherTower(), PowerfulArcherTower(), DamageTower(), RangeTower()]
TypeError: __init__() missing 2 required positional arguments: 'x' and 'y'