Menu update
silly typo. Missing bracket

Traceback (most recent call last):
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 534, in <module>
    g.run()
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 90, in run
    self.draw()
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 100, in draw
    towers.draw(self.win)
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 404, in draw
    super().draw(win)
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 346, in draw
    self.menu.draw(win)
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 168, in draw
    win.blit(text, item.x + item.width + 1, item.y + star_img.get_height())
TypeError: invalid destination position for blit