Functionality of money
Trying to make it so that you can only purchase upgrades if you have enough money. Then when a purchase is made the players money is subtracted.

However, when the player has enough money and clicks upgrade the game crashes as the menu class does not have  a get_upgrade_ cost atrribute.

Traceback (most recent call last):
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 564, in <module>
    g.run()
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 49, in run
    cost = self.selected_tower.menu.get_upgrade_cost
AttributeError: 'Menu' object has no attribute 'get_upgrade_cost'