Menu update
Needs to be a string

Traceback (most recent call last):
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 534, in <module>
    g.run()
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 90, in run
    self.draw()
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 100, in draw
    towers.draw(self.win)
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 404, in draw
    super().draw(win)
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 346, in draw
    self.menu.draw(win)
  File "/Users/Max/Documents/GitHub/Yr12ComputerScience/Alevel project/Realm defender.py", line 167, in draw
    text = self.font.render(self.item_cost[self.tower.level - 1], 1, (255,255,255))
TypeError: text must be a unicode or bytes